### ISSUE TITLE
AttributeError: module 'eigenpy' has no attribute 'switchToNumpyArray'

### ISSUE THREAD

**Issue by Boogard2021** [Gepetto/quadruped-reactive-walking#12]
Hi 
I hope you are doing well. I am in the process of installing the framework. I faced with this error. Do you know what is its reason? Thanks for your help.

hossein@hossein-ROG-Zephyrus-M16-GU603ZW-GU603ZW:~/quadruped-reactive-walking$ python3.8 -m quadruped_reactive_walking.main_solo12_control
pybullet build time: Oct  8 2020 00:11:27
Analysis: 1.5 0.0 0.0
Could not open joystick: No such file or directory
Set parameter Username
Academic license - for non-commercial use only - expires 2024-07-04
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/quadruped_reactive_walking/main_solo12_control.py", line 289, in <module>
    f, v = control_loop(np.array([1.5, 0.0, 0.0, 0.0, 0.0, 0.0]))  # , np.array([1.5, 0.0, 0.0, 0.0, 0.0, 0.0]))
  File "/usr/local/lib/python3.8/site-packages/quadruped_reactive_walking/main_solo12_control.py", line 143, in control_loop
    controller = Controller(params, q_init, 0.0)
  File "/usr/local/lib/python3.8/site-packages/quadruped_reactive_walking/Controller.py", line 92, in __init__
    from .solo3D.SurfacePlannerWrapper import Surface_planner_wrapper
  File "/usr/local/lib/python3.8/site-packages/quadruped_reactive_walking/solo3D/SurfacePlannerWrapper.py", line 10, in <module>
    from .SurfacePlanner import SurfacePlanner
  File "/usr/local/lib/python3.8/site-packages/quadruped_reactive_walking/solo3D/SurfacePlanner.py", line 10, in <module>
    from hpp.corbaserver.rbprm.tools.surfaces_from_path import getAllSurfacesDict
  File "/opt/openrobots/lib/python3.8/site-packages/hpp/corbaserver/rbprm/tools/surfaces_from_path.py", line 8, in <module>
    eigenpy.switchToNumpyArray()
AttributeError: module 'eigenpy' has no attribute 'switchToNumpyArray'

**Comment by nim65s** [comment]
Hi,

hpp-rbprm-corba currently has maintenance issues, so we might expect things like this.

The current one is that your eigenpy version is probably >= 3 and `switchToNumpyArray()` is not available anymore, but that's the default behaviour anyways, so its just fine to workaround your issue with `sudo sed -i 8d /opt/openrobots/lib/python3.8/site-packages/hpp/corbaserver/rbprm/tools/surfaces_from_path.py`

**Comment by Boogard2021** [comment]
Perfect. Thanks a lot.
